sudo: required

services:
  - docker

before_install:
  - docker build -t holbora/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run holbora/react-test npm test -- --coverage

after_success:
  - docker build -t holbora/multi-client ./client
  - docker build -t holbora/multi-nginx ./nginx
  - docker build -t holbora/multi-server ./server
  - docker build -t holbora/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push holbora/multi-client
  - docker push holbora/multi-nginx
  - docker push holbora/multi-server
  - docker push holbora/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-970251424830
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
