sudo: required

services:
  - docker

before_install:
  - docker build -t holbora/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run holbora/react-test npm test -- --coverage

after_success:
  - docker build -t holbora/multi-client ./client
  - docker build -t holbora/multi-nginx ./nginx
  - docker build -t holbora/multi-server ./server
  - docker build -t holbora/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push holbora/multi-client
  - docker push holbora/multi-nginx
  - docker push holbora/multi-server
  - docker push holbora/multi-worker


