version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=pass
  
  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      context:  ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=pass
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app